
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

#  jaeger-all-in-one:
#    image: jaegertracing/all-in-one:latest
#    restart: always
#    ports:
#      - "16686:16686"
#      - "14268" # thrift_http ????
#      - "14250" # grpc ???

  otel-collector:
    container_name: collector
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "55679:55679" # webview for traces
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver

  service-a:
    container_name: temp-otel
    #image: ghcr.io/airtongit/fc-otel-temp:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - "OTEL_SERVICE_NAME=service-a"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317"
      - "PORT=8080"
#    networks:
#      - net1

  service-b:
    container_name: service-b
    image: ghcr.io/airtongit/fc-temp-by-cep:latest
    depends_on:
      - otel-collector
    ports:
      - "7070:7070"
    environment:
      - "OTEL_SERVICE_NAME=service-b"
      - "OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317"
      - "WEATHER=955781466c1e414e9e9181300240806"
      - "PORT=7070"
#    networks:
#      - net1

#networks:
#  net1:
#    driver: bridge
