
services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "4317:4317"   # OTLP gRPC receiver

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

  service-a:
    image: ghcr.io/airtongit/fc-otel-temp:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
#    networks:
#      - net1

  service-b:
    image: ghcr.io/airtongit/fc-temp-by-cep:latest
    ports:
      - "7070:7070"
    environment:
      - "WEATHER=955781466c1e414e9e9181300240806"
      - "PORT=7070"
#    networks:
#      - net1

#networks:
#  net1:
#    driver: bridge
