

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
#  prometheus:
#    endpoint: "0.0.0.0:8889"
  debug:

  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

#    endpoint: jaeger-all-in-one:4317
#    tls:
#      insecure: true

processors:


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [zipkin, debug]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [logging, prometheus]
